# 01. Project Setup & Dataset Acquisition

## Research Objective
This notebook initiates the scientific workflow. Its primary objective is to verify that the virtual environment, directory structure, package versions, logging configurations, and random seeds are correctly configured. Additionally, it documents the acquisition process of the primary sEMG dataset (NinaPro DB2) and verifies raw file integrity.

## Background
In biomedical research, experimental reproducibility is a core requirement. Before executing complex signal processing or machine learning operations, we must guarantee that all execution environments (Python version, operating system, and libraries) match verified specifications, and that the dataset's checksum/metadata match the baseline configurations.

## Notebook Workflow
1. **Project Initialization**: Log operating system, python environment, execution timestamp, and active directory.
2. **Import Libraries**: Load standard and local modular packages.
3. **Project Configuration**: Load paths and global variables from `src/config.py`.
4. **Repository Verification**: Verify and initialize directory hierarchy.
5. **Package Verification**: Render dependencies and versions in a clean table.
6. **Reproducibility Settings**: Configure global seeds for generators.
7. **Logging Configuration**: Initialize logs to save under `outputs/logs/`.
8. **Dataset Acquisition Documentation**: Provide peer-reviewed documentation and instructions for obtaining the NinaPro Database.
9. **Dataset Verification**: Check for local dataset files in `data/raw/`.
10. **Dataset Metadata Generation**: Export JSON metadata summary.
11. **Project Health Check**: Compile readiness checklist.
12. **Notebook Summary**: Highlight accomplishments and outline the transition to Notebook 02.

## Expected Inputs
- None (Configuration settings and package dependencies only).

## Expected Outputs
- Formatted log file in `outputs/logs/`.
- Dataset metadata file in `outputs/reports/dataset_metadata.json`.
- Complete verified repository directory structure.

## References
1. Atzori, M., et al. "Electromyography data for non-invasive naturally-controlled robotic hand prostheses." *Scientific Data* (2014).
2. Scientific reproducibility benchmarks for biomedical signal processing.

## Section 1: Project Initialization

We extract information about the host platform, Python execution shell, and system properties to document the baseline scientific environment configuration.

In [1]:
# Code Section - System info & imports
import os
import sys
import time
import platform
from pathlib import Path

print(f"Project Title: Machine Learning-Based sEMG Prosthetic Gesture Classification")
print(f"Notebook Version: 1.0")
print(f"Execution Date/Time: {time.strftime('%Y-%m-%d %H:%M:%S')}")
print(f"Operating System: {platform.system()} {platform.release()} ({platform.machine()})")
print(f"Python Version: {sys.version}")
print(f"Current Working Directory: {os.getcwd()}")

Project Title: Machine Learning-Based sEMG Prosthetic Gesture Classification
Notebook Version: 1.0
Execution Date/Time: 2026-07-19 22:25:10
Operating System: Windows 10 (AMD64)
Python Version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Current Working Directory: E:\Bio-Mechanics\semg-prosthetic-gesture-classification\notebooks

## Section 2: Import Libraries

We import packages necessary for environment verification. Reusable custom functions are loaded from the modular package `src/utils.py`.

In [2]:
# Code Section - Path setup & local imports
# Ensure project root is in the path for reproducible module imports
project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

# Verification of local modular import capability
import src.utils
print("✔ Successfully imported modular src packages.")

✔ Successfully imported modular src packages.

## Section 3: Project Configuration

We load project-wide configuration parameters from `src/config.py` including directory paths, sampling frequency, and random seeds to prevent hard-coding values.

In [3]:
# Code Section - Load config paths
from src.config import (
    PROJECT_ROOT, DATA_DIR, RAW_DATA_DIR, INTERIM_DATA_DIR, PROCESSED_DATA_DIR,
    EXTERNAL_DATA_DIR, MODELS_DIR, OUTPUTS_DIR, FIGURES_DIR, TABLES_DIR,
    REPORTS_DIR, METRICS_DIR, LOGS_DIR, RANDOM_STATE, SAMPLING_RATE
)
print(f"Project root loaded: {PROJECT_ROOT}")
print(f"Raw data directory: {RAW_DATA_DIR}")

Project root loaded: E:\Bio-Mechanics\semg-prosthetic-gesture-classification
Raw data directory: E:\Bio-Mechanics\semg-prosthetic-gesture-classification\data\raw

## Section 4: Verify Repository Structure

We programmatically verify that all directories required for raw dataset storage, model persistence, figure outputs, and testing exist, automatically creating missing paths.

In [4]:
# Code Section - Verify Repository Structure
from src.utils import verify_directory_structure
import pandas as pd
from IPython.display import display, HTML

expected_directories = [
    DATA_DIR, RAW_DATA_DIR, INTERIM_DATA_DIR, PROCESSED_DATA_DIR, EXTERNAL_DATA_DIR,
    MODELS_DIR, OUTPUTS_DIR, FIGURES_DIR, TABLES_DIR, REPORTS_DIR, METRICS_DIR, LOGS_DIR
]

status_map = verify_directory_structure(expected_directories)

# Display structural health table
df_structure = pd.DataFrame([
    {"Directory": path.replace(str(PROJECT_ROOT) + os.sep, ""), "Status": "✔ Verified/Created" if exists else "❌ Failed"}
    for path, exists in status_map.items()
])
display(HTML(df_structure.to_html(index=False)))

## Section 5: Package Verification

To ensure scientific reproducibility, we audit the version numbers of all scientific computing, signal-processing, and machine learning dependencies.

In [5]:
# Code Section - Package Auditing
from src.utils import get_package_versions

required_packages = [
    "numpy", "pandas", "scipy", "matplotlib", "seaborn", "scikit-learn",
    "joblib", "ipykernel", "plotly", "PyWavelets", "shap", "xgboost", "lightgbm"
]

versions = get_package_versions(required_packages)

df_packages = pd.DataFrame([
    {"Dependency Package": pkg, "Installed Version": ver}
    for pkg, ver in versions.items()
])
display(HTML(df_packages.to_html(index=False)))

## Section 6: Random Seed Configuration

Reproducibility is fundamental to peer-reviewed science. We seed all pseudo-random generators (`random` and `numpy.random`) to guarantee reproducible dataset splits, initialization, and evaluation.

In [6]:
# Code Section - Set seeds
from src.utils import set_random_seeds

print(f"Seeding environment with RANDOM_STATE = {RANDOM_STATE}...")
set_random_seeds(RANDOM_STATE)
print("✔ Global random seeds successfully configured.")

Seeding environment with RANDOM_STATE = 42...
✔ Global random seeds successfully configured.

## Section 7: Logging Configuration

We configure logging to write messages to `outputs/logs/notebook_01_setup.log` to track execution milestones, warning flags, and exceptions during pipeline execution.

In [7]:
# Code Section - Logging configuration
from src.utils import setup_logging

logger = setup_logging("notebook_01_setup.log")
logger.info("Notebook 01: Project Setup and Dataset Acquisition executed.")

[2026-07-19 22:25:11] [INFO] [utils.py:68] - Logging initialized. Log file saved to: E:\Bio-Mechanics\semg-prosthetic-gesture-classification\outputs\logs\notebook_01_setup.log

[2026-07-19 22:25:11] [INFO] [2863363162.py:5] - Notebook 01: Project Setup and Dataset Acquisition executed.

# Section 8: Dataset Acquisition

## NinaPro Database (Primary Dataset)
The primary dataset selected for this project is the **NinaPro (Non-Invasive Collaborative Robotic Hand Prosthesis) Database**. 
NinaPro is an internationally recognized benchmark database for surface electromyography (sEMG) hand and wrist gesture classification.

### Why NinaPro is Selected:
- **Scientific Consensus**: Widely cited in literature (over 500 publications), enabling direct comparison of model accuracies.
- **High Channel Density**: Typically recorded using 8 to 12 active sEMG channels (e.g., Otto Bock MyoBock or Delsys Trigno systems).
- **Diverse Gestures**: Contains kinematic and muscular activations for 40+ distinct hand/wrist movements (including grasping, flexing, and extension).

### Official Access & Download:
- **Official Website**: http://ninapro.hevs.ch/
- **Licensing**: Access requires registering on the site and signing a research agreement. Therefore, automatic download cannot be implemented.
- **Target Subset**: **Database 2 (DB2)** is recommended for high-resolution studies (12 channels, 2000 Hz sampling rate, 40 subjects, 49 gestures).
- **Manual Step**: Please download the dataset MAT files for targeted subjects (e.g., `S1_E1_A1.mat`) and place them in the `data/raw/` directory.

### Expected Raw File Layout:
```text
data/raw/
├── DB2/
│   ├── S1_E1_A1.mat
│   ├── S1_E2_A1.mat
│   └── ...
└── .gitkeep
```

## Section 9: Dataset Verification

We scan the `data/raw/` folder for downloaded file sets to verify file counts, names, format extensions, and sizes.

In [8]:
# Code Section - Dataset scan & optional acquisition
from src.utils import verify_raw_dataset, download_and_extract_subject

raw_dataset_stats = verify_raw_dataset(RAW_DATA_DIR)

print(f"Auditing raw data folder: {RAW_DATA_DIR}")
if raw_dataset_stats['file_count'] == 0:
    logger.info("Raw dataset empty. Attempting public download of Subject 1 from NinaPro DB2...")
    print("⚠ Raw dataset missing. Attempting public download of Subject 1 from NinaPro DB2...")
    success = download_and_extract_subject(subject_id=1, target_dir=RAW_DATA_DIR)
    if success:
        print("✔ Subject 1 successfully downloaded and extracted.")
        raw_dataset_stats = verify_raw_dataset(RAW_DATA_DIR)
    else:
        print("❌ Automated download failed. Please manually download from http://ninapro.hevs.ch/ and extract to data/raw/")
else:
    print("✔ Raw dataset files found.")

if raw_dataset_stats['exists'] and raw_dataset_stats['file_count'] > 0:
    logger.info(f"Raw dataset verification: {raw_dataset_stats['file_count']} files verified.")
    print(f"✔ Raw files detected: {raw_dataset_stats['file_count']} files")
    print(f"✔ Total Size: {raw_dataset_stats['total_size_mb']} MB")
    print(f"✔ File Formats: {raw_dataset_stats['file_formats']}")

Auditing raw data folder: E:\Bio-Mechanics\semg-prosthetic-gesture-classification\data\raw
✔ Raw dataset files found.
[2026-07-19 22:25:11] [INFO] [1451497542.py:20] - Raw dataset verification: 121 files verified.

✔ Raw files detected: 121 files
✔ Total Size: 17460.98 MB
✔ File Formats: ['', '.mat']

## Section 10: Dataset Metadata

We export verified dataset statistics and file records as a JSON document to `outputs/reports/dataset_metadata.json` for integration into the research workflow.

In [9]:
# Code Section - Metadata Export
import json

metadata = {
    "dataset_name": "NinaPro Database",
    "version": "DB2",
    "download_date": time.strftime('%Y-%m-%d'),
    "raw_directory": str(RAW_DATA_DIR),
    "file_count": raw_dataset_stats['file_count'],
    "total_size_mb": raw_dataset_stats['total_size_mb'],
    "file_formats": raw_dataset_stats['file_formats']
}

metadata_file_path = REPORTS_DIR / "dataset_metadata.json"
with open(metadata_file_path, "w", encoding="utf-8") as f:
    json.dump(metadata, f, indent=4)

logger.info(f"Dataset metadata written to: {metadata_file_path}")
print(f"✔ Metadata successfully written to: {metadata_file_path}")

[2026-07-19 22:25:11] [INFO] [1663274324.py:18] - Dataset metadata written to: E:\Bio-Mechanics\semg-prosthetic-gesture-classification\outputs\reports\dataset_metadata.json

✔ Metadata successfully written to: E:\Bio-Mechanics\semg-prosthetic-gesture-classification\outputs\reports\dataset_metadata.json

## Section 11: Project Health Check

We execute a project-wide configuration review checklist to verify overall project status.

In [10]:
# Code Section - Health Check
health_checklist = {
    "Virtual Environment Active": hasattr(sys, 'real_prefix') or (sys.base_prefix != sys.prefix),
    "Required Packages Installed": all(v != "Not Installed" for v in versions.values()),
    "Repository Structure Valid": all(status_map.values()),
    "Dataset Located": raw_dataset_stats['file_count'] > 0,
    "Logging Configured": len(logger.handlers) > 0,
    "Configuration Loaded": PROJECT_ROOT.exists()
}

df_health = pd.DataFrame([
    {"Requirement Checked": k, "Readiness Status": "✔ Ready" if v else "❌ Action Required"}
    for k, v in health_checklist.items()
])
display(HTML(df_health.to_html(index=False)))

if all(health_checklist.values()):
    print("🚀 Project is FULLY READY for execution of subsequent notebooks.")
else:
    print("⚠ Repository structure & dependencies verified, but dataset is not yet downloaded.")

🚀 Project is FULLY READY for execution of subsequent notebooks.

# Section 12: Notebook Summary

## What Was Accomplished:
- **Environment Verification**: Successfully loaded system characteristics and validated the Python virtual environment.
- **Repository Structure Verification**: Programmatically checked for all 12 key project directories and automatically generated folders where missing.
- **Package Version Audit**: Checked scientific, signal-processing, and machine learning packages and compiled a markdown version table.
- **Reproducibility Configuration**: Configured random seed variables (`RANDOM_STATE = 42`) for standard scientific packages.
- **Logging Integration**: Hooked up file and stdout logging outputs to save to `outputs/logs/notebook_01_setup.log`.
- **Dataset Acquisition Documentation**: Added details on the acquisition of the NinaPro Database subset.
- **Dataset Verification**: Created a scanning module that checks `data/raw/` files and outputs size/extension summaries.
- **Metadata Export**: Exported dataset status and size summaries to `outputs/reports/dataset_metadata.json`.
- **Project Readiness Audit**: Outputted a clean health-check checklist to verify pipeline reproducibility.

## Files Created:
- `outputs/logs/notebook_01_setup.log`
- `outputs/reports/dataset_metadata.json`
- `notebooks/01_project_setup_and_dataset_acquisition.ipynb`

## Files Modified:
- `src/config.py`
- `src/utils.py`

## Connection to the Next Notebook:
The verified environment, configured paths, logging infrastructure, and random seeds established in this notebook will be used directly by **02_dataset_exploration.ipynb** to load, explore, and analyze dataset characteristics.